services:
  rust:
    build:
      context: .
      dockerfile: rust.dockerfile
    volumes:
      - ./:/workdir
    working_dir: /workdir
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ai-toolkit-network

  pandoc:
    build:
      context: .
      dockerfile: pandoc.dockerfile
    volumes:
      - ./:/workdir
    tty: true
    ports:
      - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ai-toolkit-network

networks:
  ai-toolkit-network: 
    external: true