# fly.toml file generated for md-to-pdf on 2022-08-26T13:27:59+02:00

app = "md-to-pdf"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # Ensure CORS headers are also sent when the application is down
  [services.ports.http_options.response.headers]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, OPTIONS"
  Access-Control-Allow-Headers = "*"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
