name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Choose nightly
      run: rustup update && cargo update && rustup override set nightly
    - name: Build
      run: cargo build --verbose
